Pod : Pod {
  text: CPU: 10
}

Nodes: Node Pool {
  Node1 : Node1 {
    style {
      3d: true
    }
    text: CPU: 4
  }

  Node2 : Node2 {
    style {
      3d: true
    }
    text: CPU: 4
  }

  Node3 : Node3 {
    style {
      3d: true
    }
    text: CPU: 12
  }

  Node4 : Node4 {
    style {
      3d: true
    }
    text: CPU: 16
  }
}