Node1: Backend {
  IP: 10.32.0.14
  kube-proxy: {
    text: "10.32.0.15 : 10.96.0.12"
  }
}
Node2: Database {
  IP: 10.32.0.15
  kube-proxy: {
    text: "10.32.0.14 : 10.96.0.12"
  }
}
network: Pod Network {
  shape: cloud
}

db: Service:DB {
  text: "10.96.0.12"
}

Node1 -- network
Node2 -- network

Node1.kube-proxy -- db
Node2.kube-proxy -- db
