CP: Cluster Control Plane {
  kube-apiserver
  kube-scheduler

  kube-scheduler -> kube-apiserver
}

Nodes: Worker Node Pool {
  Node1 {
    kubelet
    runtime-engine {
      CRI-O
      docker
      Podman
    }
  }

  Node2 {
    kubelet
    runtime-engine {
      CRI-O
      docker
      Podman
    }
  }
}

CP.kube-apiserver -> Nodes.Node1.kubelet
Nodes.Node1.kubelet -> Nodes.Node1.runtime-engine.docker