Node1 : Backend{
  text: "10.32.0.14"
}
Node2 : Database{
  text: "10.32.0.15"
}
network: Pod Network {
  shape: cloud
}

db : Service:DB {
  text: "10.96.0.12"
}

Node1 -- network
Node2 -- network

Node1 -- db
Node2 -- db